#!/usr/bin/env bash
# Pings an IP address (given as the first argument) 5 times.
# Prints a usage message if no argument was given.

if [ -z "$1" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

ping -c 5 "$1"