#!/usr/bin/env bash
# Configures /etc/hosts so that localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

sed '/localhost/d; /facebook.com/d' /etc/hosts > /tmp/hosts.tmp
cat /tmp/hosts.tmp > /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
